### ISSUE TITLE
Use __dirname in glsl paths

### ISSUE THREAD

**Issue by deathcap** [voxel/voxel-shader#12]
https://github.com/stackgl/glslify#browserify-transform uses `__dirname + ` for shader filename paths:

```javascript
var src = glslify(__dirname + '/shader.glsl')
```

voxel-shader probably should to, instead of `./` relative:

```javascript
    glslify('./lib/ao.vsh'),
    glslify('./lib/ao.fsh')
```

**Comment by deathcap** [comment]
Strange, tried this:

```
+++ b/aoshader.js
@@ -141,8 +141,8 @@ ShaderPlugin.prototype.render = function() {
 
 ShaderPlugin.prototype.createAOShader = function() {
     return glShader(this.shell.gl ,
-    glslify('./lib/ao.vsh'),
-    glslify('./lib/ao.fsh')
+    glslify(__dirname + 'lib/ao.vsh'),
+    glslify(__dirname + 'lib/ao.fsh')
     )

```

but then beefy vmv inexplicably fails:

```
> voxelmetaverse@0.0.1 start voxel/voxelmetaverse
> beefy index.coffee:bundle.js --watchify --port 8080 -- --debug

beefy (v2.1.5) is listening on http://127.0.0.1:8080
200  293ms       778B  /
200  818ms     7.08KB  /logo-white.png
200  814ms    16.29KB  /crosshair4.png
buffer.js:237
    buf.copy(buffer, pos);
        ^

TypeError: buf.copy is not a function
  at Function.Buffer.concat (buffer.js:237:9)
  at Stream.end (voxel/voxelmetaverse/node_modules/beefy/lib/accumulate-error.js:25:26)
  at _end (voxel/voxelmetaverse/node_modules/beefy/node_modules/through/index.js:61:9)
  at Stream.stream.end (voxel/voxelmetaverse/node_modules/beefy/node_modules/through/index.js:70:5)
  at Stream.onend (stream.js:59:10)
  at emitNone (events.js:72:20)
  at Stream.emit (events.js:166:7)
  at drain (voxel/voxelmetaverse/node_modules/beefy/node_modules/through/index.js:33:23)
  at Stream.stream.queue.stream.push (voxel/voxelmetaverse/node_modules/beefy/node_modules/through/index.js:41:5)
  at Stream.end (voxel/voxelmetaverse/node_modules/beefy/node_modules/through/index.js:17:35)
  at _end (voxel/voxelmetaverse/node_modules/beefy/node_modules/through/index.js:61:9)
  at Stream.stream.end (voxel/voxelmetaverse/node_modules/beefy/node_modules/through/index.js:70:5)
  at voxel/voxelmetaverse/node_modules/beefy/lib/bundlers/watchify.js:79:39
  at nextTickCallbackWith0Args (node.js:433:9)
  at process._tickCallback (node.js:362:13)
```

**Comment by timoxley** [comment]
@deathcap that bufcopy issue is a bug in the stream handling inside beefy (cc @chrisdickinson) because there's an error String coming out of the build, rather than a Buffer.
